# install and configure modules
- name: Populate service facts
  ansible.builtin.service_facts:

# - name: Print service facts
#   ansible.builtin.debug:
#     var: ansible_facts.services

# Execute Host based task using variable
- name: Execute the command only nginx server
  shell: cat /etc/nginx/nginx.conf
  when: {{ ansible_facts.services["nginx.service"] }} is defined 
           #ansible_facts.services["oracle-tfa.service"]
  register: ngx_conf