##DATABASES stop##
- name: stop postgresql
  ansible.builtin.service:
    name: postgresql
    state: stopped
when: db_type == "postgresql"

# - name: stop oracle
#   ansible.builtin.service:
#     name: postgresql
#     state: stopped
# when: db_type == "oracle"

#Create vmware snapshot
- name: Create a snapshot
  community.vmware.vmware_guest_snapshot:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username  }}"
    password: "{{ vcenter_password }}"
    datacenter: "MCB" #{{ datacenter_name }}"
    folder: "/MCB/vm/" 
    name: "{{ inventory_hostname }}"
    state: present
    snapshot_name: "awx_snapshot_{{ ansible_date_time.date }}"
    description: "{{ ansible_date_time.date }} {{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}"
    validate_certs: no
delegate_to: localhost

##RHEL/OEL BLOCK
- block

    #Remove zabbix external repo package
    - name: Remove zabbix repo dummy package
      yum:
        name: 'zabbix-release'
        state: absent
      ignore_errors: yes
      become: yes

    #Update all RPM packages
    - name: Update all RPM packages
      yum:
        name: "*"
        state: latest
        exclude: "{{ exclude_pakages }}"
        skip_broken: "{{ skip_broken }}"
        disablerepo: "{{ disable_repos }}"
        enablerepo: "{{ enable_repos }}"
      notify:
        - reboot
        - reboot rhel6

when: ansible_distribution == "RedHat" or ansible_distribution == "Oracle linux"

#FREEBSD BLOCK
- block
    - name: Upgrade all installed packages (see warning for the name option first!)
      community.general.pkgng:
        name: "*"
        state: latest
      notify:
        - reboot
when: ansible_distribution == "FreeBSD"

